// Auto-generated by: npm run db:types
// Run `supabase gen types typescript --local > src/types/database.types.ts` to regenerate.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          full_name: string
          phone: string | null
          second_phone: string | null
          email: string | null
          avatar_url: string | null
          role: 'citizen' | 'provider' | 'admin'
          village: string | null
          gender: string | null
          birth_date: string | null
          national_id: string | null
          id_front_url: string | null
          id_back_url: string | null
          identity_verified: boolean
          identity_verified_at: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['profiles']['Row'], 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
